apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: kafka
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/scheme: internet-facing
    nginx.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: mykafka.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kakfa-svc
            port:
              number: 9092
